import type { Metadata, Viewport } from "next";
import { Cormorant_Garamond, Cinzel, Inter } from "next/font/google";
import "./globals.css";
import IntroProvider from "@/components/IntroProvider";
import { site } from "@/lib/site";

// Display headlines — editorial serif
const cormorant = Cormorant_Garamond({
  variable: "--font-cormorant",
  subsets: ["latin"],
  display: "swap",
  weight: ["400", "500", "600"],
});

// Eyebrows / labels / nav — tracked caps
const cinzel = Cinzel({
  variable: "--font-cinzel-src",
  subsets: ["latin"],
  display: "swap",
  weight: ["400", "500", "600"],
});

// Body / UI
const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
  display: "swap",
});

const title = `${site.name} — ${site.tagline}`;

export const metadata: Metadata = {
  metadataBase: new URL(site.url),
  title: {
    default: title,
    template: `%s · ${site.name}`,
  },
  description: site.description,
  applicationName: site.name,
  keywords: [
    "interior design studio",
    "interior designer",
    "residential interior design",
    "hospitality interior design",
    "restaurant interior design",
    "café interior design",
    "lounge and bar design",
    "bakery interior design",
    "loft interior design",
    "wellness and spa design",
    "luxury interiors",
    "space planning",
    "3D visualisation",
  ],
  authors: [{ name: site.name, url: site.url }],
  creator: site.name,
  publisher: site.name,
  category: "Interior Design",
  alternates: { canonical: "/" },
  formatDetection: { telephone: false, email: false, address: false },
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      "max-image-preview": "large",
      "max-snippet": -1,
      "max-video-preview": -1,
    },
  },
  openGraph: {
    type: "website",
    locale: "en_GB",
    url: site.url,
    siteName: site.name,
    title,
    description: site.description,
    // The branded share card is generated by app/opengraph-image.tsx.
  },
  twitter: {
    card: "summary_large_image",
    title,
    description: site.description,
    // The card image is generated by app/twitter-image.tsx.
  },
  appleWebApp: {
    capable: true,
    title: site.name,
    statusBarStyle: "black-translucent",
  },
};

export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
  colorScheme: "dark",
  themeColor: "#0a1124",
};

// Structured data for rich results — describes the studio + the site.
const jsonLd = {
  "@context": "https://schema.org",
  "@graph": [
    {
      "@type": ["Organization", "ProfessionalService"],
      "@id": `${site.url}/#organization`,
      name: site.name,
      url: site.url,
      description: site.description,
      logo: `${site.url}/logo-mark.svg`,
      image: `${site.url}/opengraph-image`,
      email: site.email,
      telephone: site.phone,
      address: {
        "@type": "PostalAddress",
        streetAddress: "Studio 04, Harbour Lane",
        addressLocality: "London",
        addressCountry: "GB",
      },
      areaServed: "Worldwide",
      knowsAbout: [
        "Residential Interior Design",
        "Hospitality Interior Design",
        "Restaurant Design",
        "Café Design",
        "Lounge & Bar Design",
        "Wellness & Spa Design",
      ],
    },
    {
      "@type": "WebSite",
      "@id": `${site.url}/#website`,
      url: site.url,
      name: title,
      description: site.description,
      publisher: { "@id": `${site.url}/#organization` },
      inLanguage: "en-GB",
    },
  ],
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en-GB"
      className={`${cormorant.variable} ${cinzel.variable} ${inter.variable} h-full`}
    >
      <body
        suppressHydrationWarning
        className="min-h-full flex flex-col bg-ink text-beige antialiased"
      >
        <script
          type="application/ld+json"
          // Structured data is static, build-time JSON — safe to inline.
          dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }}
        />
        <IntroProvider>{children}</IntroProvider>
      </body>
    </html>
  );
}
